
import java.text.MessageFormat;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Seema.Sd
 */
public class JavaPOS extends javax.swing.JFrame {

    private Object PriceOfItem;

    /**
     * Creates new form JavaPOS
     */
    public JavaPOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnnexium = new javax.swing.JButton();
        jbtndiprovate = new javax.swing.JButton();
        jbtncetrizine = new javax.swing.JButton();
        jbtntrivolib = new javax.swing.JButton();
        jbtnamlodipine = new javax.swing.JButton();
        jbtnglucophage = new javax.swing.JButton();
        jbtnzolpidem = new javax.swing.JButton();
        jbtnnovidat = new javax.swing.JButton();
        jbtnherbodil = new javax.swing.JButton();
        jbtnpiroxicam = new javax.swing.JButton();
        jbtnmetformin = new javax.swing.JButton();
        jbtnfabi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbtn9 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtndot = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel35 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtSubTotal = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jtxtTotal = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxtDisplay = new javax.swing.JTextField();
        jtxtChange = new javax.swing.JTextField();
        jcboPayment = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jbtnReset = new javax.swing.JButton();
        jbtnRemove = new javax.swing.JButton();
        jbtnPay = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxtCphone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtCname = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnnexium.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnnexium.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nexium (1).jpg"))); // NOI18N
        jbtnnexium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnnexiumActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnnexium, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 160, 90));

        jbtndiprovate.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtndiprovate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/diprovate (1).jpg"))); // NOI18N
        jbtndiprovate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndiprovateActionPerformed(evt);
            }
        });
        jPanel1.add(jbtndiprovate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, 90));

        jbtncetrizine.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtncetrizine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cetrizine (3).jpg"))); // NOI18N
        jbtncetrizine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncetrizineActionPerformed(evt);
            }
        });
        jPanel1.add(jbtncetrizine, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 160, 90));

        jbtntrivolib.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtntrivolib.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/trivolib (1).jpg"))); // NOI18N
        jbtntrivolib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtntrivolibActionPerformed(evt);
            }
        });
        jPanel1.add(jbtntrivolib, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 160, 90));

        jbtnamlodipine.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnamlodipine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/amlodiphine (1).jpg"))); // NOI18N
        jbtnamlodipine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnamlodipineActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnamlodipine, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 160, 90));

        jbtnglucophage.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnglucophage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/glucophage (1).jpg"))); // NOI18N
        jbtnglucophage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnglucophageActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnglucophage, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 160, 90));

        jbtnzolpidem.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnzolpidem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/zolpidem (1).jpg"))); // NOI18N
        jbtnzolpidem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnzolpidemActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnzolpidem, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 160, 90));

        jbtnnovidat.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnnovidat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/novidat (1).jpg"))); // NOI18N
        jbtnnovidat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnnovidatActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnnovidat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 160, 90));

        jbtnherbodil.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnherbodil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/herbodil (1).jpeg"))); // NOI18N
        jbtnherbodil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnherbodilActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnherbodil, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 160, 90));

        jbtnpiroxicam.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnpiroxicam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/piroxicam (1).jpg"))); // NOI18N
        jbtnpiroxicam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnpiroxicamActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnpiroxicam, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 160, 90));

        jbtnmetformin.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnmetformin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/metformin.jpeg"))); // NOI18N
        jbtnmetformin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmetforminActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnmetformin, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 160, 90));

        jbtnfabi.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnfabi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fabi (1).jpg"))); // NOI18N
        jbtnfabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnfabiActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnfabi, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 160, 90));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("₹68");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("₹24");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("₹500");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("₹230");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("₹1200");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 121, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("₹653");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel15.setText("₹67");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 50, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("₹1007");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, -1, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setText("₹280");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel18.setText("₹651");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, 20));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setText("₹87");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setText("₹498");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, -1, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 850, 410));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 70, 100));

        jbtn7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 100));

        jbtn8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 70, 100));

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton5.setText("7");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 70));

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton6.setText("7");
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 70, 70));

        jbtn4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 70, 100));

        jbtn5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 70, 100));

        jbtn6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 70, 100));

        jbtn1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 70, 100));

        jbtn2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 70, 100));

        jbtn3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 70, 100));

        jbtn0.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 70, 100));

        jbtndot.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtndot.setText(".");
        jbtndot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndotActionPerformed(evt);
            }
        });
        jPanel2.add(jbtndot, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 70, 100));

        jbtnC.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnC.setText("C");
        jbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 70, 100));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 260, 430));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(0, 204, 204));
        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ITEM", "QUANTITY", "AMOUNT"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 330, 270));

        jPanel35.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("SubTotal");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Tax");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Total");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jtxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSubTotalActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 15, 190, 40));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField3.setText("jTextField1");
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 15, 190, 40));

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTaxActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 190, 40));

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 190, 40));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setText("SubTotal");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel22.setText("SubTotal");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel35.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 400, 200));

        jPanel4.setBackground(new java.awt.Color(255, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Payment Method");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Cash");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Change");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jtxtDisplay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel4.add(jtxtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 210, 40));

        jtxtChange.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel4.add(jtxtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 210, 40));

        jcboPayment.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jcboPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Visa Card", "Master Card" }));
        jPanel4.add(jcboPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 140, 30));

        jPanel35.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 370, 200));

        jPanel5.setBackground(new java.awt.Color(255, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 200, 60));

        jbtnRemove.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnRemove.setText("Remove");
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 200, 60));

        jbtnPay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPay.setText("Pay");
        jbtnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPayActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 200, 60));

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 430, 60));

        jbtnPrint.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 200, 60));

        jPanel35.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, 480, 200));

        getContentPane().add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 1380, 310));

        jPanel6.setBackground(new java.awt.Color(102, 153, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("NAME");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jtxtCphone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtCphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCphoneActionPerformed(evt);
            }
        });
        jPanel6.add(jtxtCphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 210, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("PHONE");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jtxtCname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtCname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCnameActionPerformed(evt);
            }
        });
        jPanel6.add(jtxtCname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 12, 220, 40));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 320, 130));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //=====================Function=================================
    private double points;
    public void ItemCost()
    {
        double sum=0;
        for(int i=0;i<jTable1.getRowCount();i++)
        {
            sum=sum+Double.parseDouble(jTable1.getValueAt(i,2).toString());
        }
        jtxtSubTotal.setText(Double.toString(sum));
        double cTotal1=Double.parseDouble(jtxtSubTotal.getText());
    
        
        
        double cTax=(cTotal1 * 3.9)/100;
        String iTaxTotal=String.format("₹ %.2f",cTax);
        jtxtTax.setText(iTaxTotal);
        
        String iSubTotal=String.format("₹ %.2f",cTotal1);
        jtxtSubTotal.setText(iSubTotal);
        points=cTotal1+cTax;
        String iTotal=String.format("₹ %.2f",cTotal1+cTax);
        jtxtTotal.setText(iTotal);
        
    }
    
    
    //=====================Function Change=================================
    public double Change()
    {
        double sum=0;
        double tax=3.9;
        double cash=Double.parseDouble(jtxtDisplay.getText());
        
         for(int i=0;i<jTable1.getRowCount();i++)
        {
            sum=sum+Double.parseDouble(jTable1.getValueAt(i,2).toString());
        }
        double cTax=(sum * 3.9)/100;
        double cChange=(cash-(sum+cTax));
        
        return cChange;
    }
    
    
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        if(Enternumber=="")
        {
            jtxtDisplay.setText(jbtn7.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText()+jbtn7.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
         String Enternumber = jtxtDisplay.getText();
        if(Enternumber=="")
        {
            jtxtDisplay.setText(jbtn4.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText()+jbtn4.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
         String Enternumber = jtxtDisplay.getText();
        if(Enternumber=="")
        {
            jtxtDisplay.setText(jbtn1.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText()+jbtn1.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
         String Enternumber = jtxtDisplay.getText();
        if(Enternumber=="")
        {
            jtxtDisplay.setText(jbtn0.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText()+jbtn0.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnamlodipineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnamlodipineActionPerformed
        
        double priceOfItem=67;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Amlodipine","1",priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnamlodipineActionPerformed

    private void jbtnherbodilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnherbodilActionPerformed
        double priceOfItem=87;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"herbodil","1",priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnherbodilActionPerformed

    private void jtxtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSubTotalActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
         String Enternumber = jtxtDisplay.getText();
        if(Enternumber=="")
        {
            jtxtDisplay.setText(jbtn8.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText()+jbtn8.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
         String Enternumber = jtxtDisplay.getText();
        if(Enternumber=="")
        {
            jtxtDisplay.setText(jbtn9.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText()+jbtn9.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn9ActionPerformed
private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame=new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Point of Sale",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jtxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalActionPerformed

    private void jbtnmetforminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmetforminActionPerformed
        double priceOfItem=1007;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"metformin","1",priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnmetforminActionPerformed

    private void jbtnglucophageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnglucophageActionPerformed
        double priceOfItem=280;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"glucophage","1",priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnglucophageActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
         String Enternumber = jtxtDisplay.getText();
        if(Enternumber=="")
        {
            jtxtDisplay.setText(jbtn5.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText()+jbtn5.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
         String Enternumber = jtxtDisplay.getText();
        if(Enternumber=="")
        {
            jtxtDisplay.setText(jbtn6.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText()+jbtn6.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
         String Enternumber = jtxtDisplay.getText();
        if(Enternumber=="")
        {
            jtxtDisplay.setText(jbtn2.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText()+jbtn2.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
         String Enternumber = jtxtDisplay.getText();
        if(Enternumber=="")
        {
            jtxtDisplay.setText(jbtn3.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText()+jbtn3.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
        jtxtDisplay.setText("");
        jtxtChange.setText("");
    }//GEN-LAST:event_jbtnCActionPerformed

    private void jbtndotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndotActionPerformed
        
        if(! jtxtDisplay.getText().contains("."))
        {
             jtxtDisplay.setText(jtxtDisplay.getText()+jbtndot.getText());
        }
    }//GEN-LAST:event_jbtndotActionPerformed

    private void jbtndiprovateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndiprovateActionPerformed
        double priceOfItem=68;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"diprovate","1",priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtndiprovateActionPerformed

    private void jbtncetrizineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncetrizineActionPerformed
        double priceOfItem=24;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"cetrizine","1",priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtncetrizineActionPerformed

    private void jbtnfabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnfabiActionPerformed
        double priceOfItem=1200;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"fabi","1",priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnfabiActionPerformed

    private void jbtnnexiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnnexiumActionPerformed
        double priceOfItem=500;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"nexium","1",priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnnexiumActionPerformed

    private void jbtntrivolibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtntrivolibActionPerformed
        double priceOfItem=653;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"trivolib","1",priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtntrivolibActionPerformed

    private void jbtnzolpidemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnzolpidemActionPerformed
        double priceOfItem=230;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"zolpidem","1",priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnzolpidemActionPerformed

    private void jbtnnovidatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnnovidatActionPerformed
        double priceOfItem=651;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"novidat","1",priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnnovidatActionPerformed

    private void jbtnpiroxicamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnpiroxicamActionPerformed
       double priceOfItem=498;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"piroxicam","1",priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnpiroxicamActionPerformed

    private void jbtnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPayActionPerformed
        if(jcboPayment.getSelectedItem().equals("Cash"))
        {
            double cChange=Change();
            if(cChange<0)
            {
                JOptionPane.showMessageDialog(frame, "Amount is not sufficient","Warning",JOptionPane.WARNING_MESSAGE);
                jtxtDisplay.setText("");
            }
            else
            {
                String cg=String.format("₹ %.2f" ,cChange);
                jtxtChange.setText(cg);
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.addRow(new Object[]{"Gross Total","",jtxtSubTotal.getText()});
                model.addRow(new Object[]{"TAX Added","",jtxtTax.getText()});
                model.addRow(new Object[]{"Net Total","",jtxtTotal.getText()});
                model.addRow(new Object[]{"Mode of Payment","",jcboPayment.getSelectedItem()});
                model.addRow(new Object[]{"Received","","₹ "+jtxtDisplay.getText()});
            }
        }
        else
        {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.addRow(new Object[]{"Gross Total","",jtxtSubTotal.getText()});
                model.addRow(new Object[]{"G.S.T Added","",jtxtTax.getText()});
                model.addRow(new Object[]{"Net Total","",jtxtTotal.getText()});
                model.addRow(new Object[]{"Mode of Payment","",jcboPayment.getSelectedItem()});
                model.addRow(new Object[]{"Credited Amount","","₹ "+jtxtDisplay.getText()});
                jtxtChange.setText("");
                jtxtDisplay.setText("");
                }
       
    }//GEN-LAST:event_jbtnPayActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        jtxtChange.setText("");
        jtxtTax.setText("");
        jtxtTotal.setText("");
        jtxtSubTotal.setText("");
        jtxtDisplay.setText("");
        
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
 
        if(jTable1.getRowCount()==0)
        {
            JOptionPane.showMessageDialog(frame,"Please Select Items to order","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if("".equals(jtxtCname.getText()) && "".equals(jtxtCphone.getText()))
        {
            JOptionPane.showMessageDialog(frame,"Customer Name and Contact Number is required","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if("".equals(jtxtCname.getText()))
        {
            JOptionPane.showMessageDialog(frame,"Customer Name is required","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(jtxtCname.getText().length()>0){
            if(jtxtCname.getText().contains(" "))
            {
                
                String[] arr = jtxtCname.getText().split(" ");
                for(String str:arr)
                {
                    if(!Pattern.matches("[a-zA-Z]+",str))
                    {
                        JOptionPane.showMessageDialog(frame,"Customer Name is should contain only alphabets","Warning",JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                }
            }
            else
            {
                if(!Pattern.matches("[a-zA-Z]+",jtxtCname.getText()))
                {
                    JOptionPane.showMessageDialog(frame,"Customer Name is should contain only alphabets","Warning",JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
        }
        if("".equals(jtxtCphone.getText()))
        {
            JOptionPane.showMessageDialog(frame,"Customer Contact number is required","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!Pattern.matches("[0-9]+",jtxtCphone.getText()))
                {
                    JOptionPane.showMessageDialog(frame,"Contact number should contain only digits","Warning",JOptionPane.WARNING_MESSAGE);
                    return;
                }
        if(jtxtCphone.getText().length() != 10)
        {
            JOptionPane.showMessageDialog(frame,"Customer Contact number should be 10 digits","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        points = points*(0.2);

        MessageFormat header = new MessageFormat("M.S.L SHOP NO.40 ROYAL STREET NELLORE");
        MessageFormat footer = new MessageFormat("Customer Name : "+jtxtCname.getText()+" Phone Number: "+jtxtCphone.getText()+" Received Points : "
        +Double.toString(points));

        try
        {
            jTable1.print(JTable.PrintMode.NORMAL,header,footer);
        }
        catch(java.awt.print.PrinterException e)
        {
            System.err.format("No Printer Found", e.getMessage());
        }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        int RemoveItem=jTable1.getSelectedRow();
        if(RemoveItem>=0)
        {
            model.removeRow(RemoveItem);
        }
        ItemCost();
        
        if(jcboPayment.getSelectedItem().equals("Cash"))
        {
            Change();
        }
        else
        {
            jtxtChange.setText("");
            jtxtDisplay.setText("");
                }
       
    }//GEN-LAST:event_jbtnRemoveActionPerformed

    private void jtxtTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTaxActionPerformed

    private void jtxtCphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCphoneActionPerformed

    private void jtxtCnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaPOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnPay;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnamlodipine;
    private javax.swing.JButton jbtncetrizine;
    private javax.swing.JButton jbtndiprovate;
    private javax.swing.JButton jbtndot;
    private javax.swing.JButton jbtnfabi;
    private javax.swing.JButton jbtnglucophage;
    private javax.swing.JButton jbtnherbodil;
    private javax.swing.JButton jbtnmetformin;
    private javax.swing.JButton jbtnnexium;
    private javax.swing.JButton jbtnnovidat;
    private javax.swing.JButton jbtnpiroxicam;
    private javax.swing.JButton jbtntrivolib;
    private javax.swing.JButton jbtnzolpidem;
    private javax.swing.JComboBox<String> jcboPayment;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtCname;
    private javax.swing.JTextField jtxtCphone;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
